name: portfolio_two
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  auto_size_text: ^3.0.0  
  bloc: ^8.0.3
  device_preview: ^1.1.0
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.0.3+1
  get_it: ^7.2.0  
  injectable: ^1.5.3
  intl: ^0.17.0


dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  build_runner:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.0.3
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
