// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBADdHRA-eavP8OaUrUohxmbRwCSbjV9Ko',
    appId: '1:319176506676:web:e4b529556c0a906f5cf961',
    messagingSenderId: '319176506676',
    projectId: 'portfolio-4fc5a',
    authDomain: 'portfolio-4fc5a.firebaseapp.com',
    storageBucket: 'portfolio-4fc5a.appspot.com',
    measurementId: 'G-CCG3SX223K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD0-3AQHvFoDgIxcyF1uw0TM9bH9wiDqg',
    appId: '1:319176506676:android:2f935d5d5885258e5cf961',
    messagingSenderId: '319176506676',
    projectId: 'portfolio-4fc5a',
    storageBucket: 'portfolio-4fc5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4jReeOHbPKg-YJauihnxXFvbysoGmW8',
    appId: '1:319176506676:ios:2d7974d91b62e1825cf961',
    messagingSenderId: '319176506676',
    projectId: 'portfolio-4fc5a',
    storageBucket: 'portfolio-4fc5a.appspot.com',
    iosClientId:
        '319176506676-v0ilqvsq92m9v7anm9vn15gu77jokqrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.portfolio-two',
  );
}
